# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12!com.epam.trainning.grpc.protocols\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x82\x01\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x39\n\x06gender\x18\x04 \x01(\x0e\x32).com.epam.trainning.grpc.protocols.Gender\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05*)\n\x06Gender\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\t\n\x05OTHER\x10\x02\x32\x80\x01\n\x0bUserService\x12q\n\x0egetUserDetails\x12..com.epam.trainning.grpc.protocols.UserRequest\x1a/.com.epam.trainning.grpc.protocols.UserResponseB%\n!com.epam.trainning.grpc.protocolsP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.epam.trainning.grpc.protocolsP\001'
  _globals['_GENDER']._serialized_start=215
  _globals['_GENDER']._serialized_end=256
  _globals['_USERREQUEST']._serialized_start=49
  _globals['_USERREQUEST']._serialized_end=80
  _globals['_USERRESPONSE']._serialized_start=83
  _globals['_USERRESPONSE']._serialized_end=213
  _globals['_USERSERVICE']._serialized_start=259
  _globals['_USERSERVICE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
